language: python
python:
  - "2.7"
install: pip install -r requirements.txt
script: 
  - python manage.py test --pattern="test*.py"
  - coverage run --source='.' manage.py test
after_success:
  - coveralls
